create extension if not exists pgcrypto;

create table if not exists public.photo_sessions (
  id bigint generated by default as identity primary key,
  session_id uuid not null default gen_random_uuid(),
  layout_id text not null check (layout_id in ('A', 'B', 'C', 'D')),
  filter_id text not null,
  total_shots integer not null check (total_shots between 1 and 8),
  created_at timestamptz not null default now()
);

create index if not exists idx_photo_sessions_session_id
  on public.photo_sessions (session_id);

create index if not exists idx_photo_sessions_created_at
  on public.photo_sessions (created_at desc);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 120),
  email text not null check (position('@' in email) > 1),
  message text not null check (char_length(message) between 10 and 3000),
  created_at timestamptz not null default now()
);

create index if not exists idx_contact_messages_created_at
  on public.contact_messages (created_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'photobooth-uploads',
  'photobooth-uploads',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
